name: Print message
'on':
  push:
    branches:
      - branch-3
jobs:
  job-demo1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Comment
        run: 'echo "Code pushed to design-changes branch!"'
